import Head from "next/head";
import React from "react";

const Seo = () => {
  return (
    <Head>
      <title>Product Preview</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Seo;
